### ISSUE TITLE
Daemon reports address is not valid

### ISSUE THREAD

**Issue by JimVanEeden** [aionnetwork/aion_miner#36]
I'm getting this error: `Daemon reports address is not valid` with the new kernel (0.3.2), so I can't run the solo pool, which means I cannot solo mine. With kernel 0.3.1, the solo_pool runs fine. I cannot upgrade to 0.3.2 kernel until this is fixed :(

**Comment by aion-Ross** [comment]
Will take a look at it and update shortly. 

Could you post your miner address or the command you're trying to run the miner with?

**Comment by jzaluski** [comment]
Confirmed error. I was able to reproduce `Daemon reports address is not valid` error with 032 and solo pool.

**Comment by JimVanEeden** [comment]
You can close this issue, as it was fixed. However, can you make a release of the latest version?

**Comment by aion-Ross** [comment]
Sorry about that, must have forgotten to put out the full release. 

0.3.2 should be published now.
