### ISSUE TITLE
 fatal error: sodium.h: No such file or directory

### ISSUE THREAD

**Issue by rnkhouse** [aionnetwork/aion_miner#6]
Getting below error when I run this command: `node-gyp build`

ronak@aion:~/aion_miner/aion_solo_pool/local_modules/equihashverify$ node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@4.2.6 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/ronak/aion_miner/aion_solo_pool/local_modules/equihashverify/build'
  CC(target) Release/obj.target/libequi/src/equi/blake2b.o
../src/equi/blake2b.c:3:20: fatal error: sodium.h: No such file or directory
compilation terminated.
libequi.target.mk:104: recipe for target 'Release/obj.target/libequi/src/equi/blake2b.o' failed
make: *** [Release/obj.target/libequi/src/equi/blake2b.o] Error 1
make: Leaving directory '/home/ronak/aion_miner/aion_solo_pool/local_modules/equihashverify/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.13.0-1007-azure
gyp ERR! command "/usr/bin/nodejs" "/usr/local/bin/node-gyp" "build"
gyp ERR! cwd /home/ronak/aion_miner/aion_solo_pool/local_modules/equihashverify
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

**Comment by JSorenSwanson** [comment]
You need to download and install the latest stable version of libsodium. 
https://download.libsodium.org/doc/

**Comment by rnkhouse** [comment]
I have installed the latest stable version and applied below commands:
`./configure
make && make check
sudo make install`

**Comment by rnkhouse** [comment]
When I run that command: `/usr/bin/sudo: /usr/bin/sudo: cannot execute binary file`

**Comment by rnkhouse** [comment]
Updated the node version and reconfigure.

gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@9.5.0 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/ronak/aion_miner/aion_solo_pool/local_modules/equihashverify/build'
  CXX(target) Release/obj.target/libequi/src/equi/equi210.o
In file included from ../src/equi/equi210.cpp:18:0:
../src/equi/equi210.h:24:35: fatal error: boost/static_assert.hpp: No such file or directory
compilation terminated.
libequi.target.mk:106: recipe for target 'Release/obj.target/libequi/src/equi/equi210.o' failed
make: *** [Release/obj.target/libequi/src/equi/equi210.o] Error 1
make: Leaving directory '/home/ronak/aion_miner/aion_solo_pool/local_modules/equihashverify/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.13.0-1007-azure
gyp ERR! command "/usr/bin/node" "/usr/local/bin/node-gyp" "build"
gyp ERR! cwd /home/ronak/aion_miner/aion_solo_pool/local_modules/equihashverify
gyp ERR! node -v v9.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

**Comment by rnkhouse** [comment]
Solved by : `sudo apt-get install libboost-all-dev`

**Comment by mauricewells** [comment]
I solved that by trying the following command
`sudo apt install libsodium-dev`
